// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzYFJl0rnFaN0mHC5Xr55-W4_eJ5yDsO0',
    appId: '1:607712690926:web:657cf1ad4897c61fce29ff',
    messagingSenderId: '607712690926',
    projectId: 'cs4720-instagram2',
    authDomain: 'cs4720-instagram2.firebaseapp.com',
    storageBucket: 'cs4720-instagram2.firebasestorage.app',
    measurementId: 'G-HP7L2Q86P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiXlL7iZCk4tZkc6B0MztnuNKaoKZaYt8',
    appId: '1:607712690926:android:3f23fd19745ec39fce29ff',
    messagingSenderId: '607712690926',
    projectId: 'cs4720-instagram2',
    storageBucket: 'cs4720-instagram2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwGH4nbReigFneyFVq8yTb7fTTt0dHsIw',
    appId: '1:607712690926:ios:cad828b5da5705a2ce29ff',
    messagingSenderId: '607712690926',
    projectId: 'cs4720-instagram2',
    storageBucket: 'cs4720-instagram2.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwGH4nbReigFneyFVq8yTb7fTTt0dHsIw',
    appId: '1:607712690926:ios:cad828b5da5705a2ce29ff',
    messagingSenderId: '607712690926',
    projectId: 'cs4720-instagram2',
    storageBucket: 'cs4720-instagram2.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzYFJl0rnFaN0mHC5Xr55-W4_eJ5yDsO0',
    appId: '1:607712690926:web:96af5c2ce8fabd33ce29ff',
    messagingSenderId: '607712690926',
    projectId: 'cs4720-instagram2',
    authDomain: 'cs4720-instagram2.firebaseapp.com',
    storageBucket: 'cs4720-instagram2.firebasestorage.app',
    measurementId: 'G-WHYD7TNCQY',
  );
}
